# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Text2Speech' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Text2Speech
    pod 'SwiftyJSON'

  target 'Text2SpeechTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
